# Generated by Django 3.0.8 on 2020-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_name', models.CharField(max_length=20)),
                ('Area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Product_name', models.CharField(max_length=20)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Shop_discription', models.CharField(max_length=200)),
                ('Pic_shop', models.FileField(upload_to='static')),
                ('pic_product', models.FileField(upload_to='static')),
            ],
        ),
    ]
