# Generated by Django 3.0.8 on 2020-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_tour', models.CharField(max_length=20)),
                ('Pic_tour', models.FileField(upload_to='static')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='Area',
            field=models.CharField(max_length=50),
        ),
    ]
